region                         = "eu-west-2"
vpc_cidr                       = "10.0.0.0/16"
public_subnet_cidr             = ["10.0.1.0/24", "10.0.2.0/24"]
public_subnet_names            = ["project-public-a", "project-public-b"]
private_subnet_cidr            = ["10.0.3.0/24", "10.0.4.0/24"]
private_subnet_names           = ["proj-private-a", "proj-private-b"]
AWS_ACCESS_KEY                 = "AKIARO5LC7RHVSM3EM6E"
AWS_SECRET_KEY                 = "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"
domain_name                    = ["eaglestbuckets", "eaglesetexbuckets"]
availability_zone              = ["eu-west-2a", "eu-west-2b"]
dockerhub_credentials          = "DevCodePipelineSecret"
codestar_connector_credentials = "arn:aws:codestar-connections:eu-west-2:100753669199:connection/5840b907-2dec-4bd1-bfad-27ad638a08d5"