version: 0.2
phases:
  pre_build:
    commands:
      - terraform init
      - terraform validate
  build:
    commands:
      - echo Apply started on `date`
      - terraform apply -auto-approve
  post_build:
    commands:
      - echo terraform $TF_COMMAND completed on `date`